version: '3'

services: 
    postgres:
        container_name: 'valcomp-search'
        restart: unless-stopped
        image: 'postgres:11'
        ports:
          # NOTE: To avoid overlapping with any Postgres database run on the host machine,
          # we bind Postgres to port "15432" instead.
          - '15432:5432'
        volumes:
          - 'pgdata:/var/lib/postgresql/data/'
        environment:
          POSTGRES_PASSWORD: postgres

volumes:
    pgdata: {}